### ISSUE TITLE
Build failure (CSS file in wrong position)

### ISSUE THREAD

**Issue by Stypox** [DMaroo/GhidRust#4]
After running `./build -g /opt/ghidra` with Gradle 8.1.1 and Java 20, I got an error related to a CSS file not being found. I can't reproduce anymore unfortunately,even after a `GHIDRA_INSTALL_DIR=/opt/ghidra gradle clean`, but the error happened while processing `src/main/help/help/topics/GhidRust/help.html`. It said that it couldn't find the file `src/main/help/help/shared/Frontpage.css` (even though it exists) and that it had  `src/main/help/help/topics/GhidRust/help/shared/DefaultStyle.css` as a candidate (which happens to be the CSS file included by the HTML). I copied over `src/main/help/help/shared/Frontpage.css` to  `src/main/help/help/topics/GhidRust/help/shared/DefaultStyle.css` and the build ran just fine.

**Comment by DMaroo** [comment]
I think a Ghidra update had something to do with it. I am not entirely sure, but depending on your Ghidra version any one of two positions would work fine.

**Comment by DMaroo** [comment]
https://github.com/DMaroo/GhidRust/commit/eb99077ee35706c0736316e6f66f0e004faa82db should fix it, please have a look. Thanks!

**Comment by DMaroo** [comment]
I am closing this issue since it seems to have been resolved. Please let me know if you are still facing problems.
