### ISSUE TITLE
How can I build it on Windows

### ISSUE THREAD

**Issue by Gift1a** [DMaroo/GhidRust#5]
How can I build it on Windows?

**Comment by DMaroo** [comment]
I really don't have a Windows setup so I don't have a way to create a build script and test it. I am pretty sure running the commands inside the `build.sh` would work. Try the following commands and please let me know.

```
gradle -PGHIDRA_INSTALL_DIR="$GHIDRA"
sudo cp dist/* "$GHIDRA"/Extensions/Ghidra
```

But you will have to figure out the value of `$GHIDRA`, the installation root, for Windows. It should be somewhere in the `C:/` directory.

**Comment by Gift1a** [comment]
Thanks for your reply.I tried to build it on linux just now. But it failed(Ghidra10.2.3) and it's the same problem as [issue](https://github.com/DMaroo/GhidRust/issues/4).

**Comment by DMaroo** [comment]
https://github.com/DMaroo/GhidRust/commit/eb99077ee35706c0736316e6f66f0e004faa82db should fix the build on Linux, please have a look. Thanks!

**Comment by Gift1a** [comment]
ohhh! I will check it tomorrow and thanks for your contribution.
