### ISSUE TITLE
Build Error: Incorrect stylesheet defined - none match

### ISSUE THREAD

**Issue by p2lu** [DMaroo/GhidRust#6]
I'm having the same issue as #4 even your patch #eb99077, i'm using Ghidra 10.2.3, Java 17 and gradle-8.1.1
Exception in thread "main" ghidra.util.exception.AssertException: Errors parsing HTML file: help.html
``Incorrect stylesheet defined - none match src/main/help/help/shared/Frontpage.css in file src/main/help/help/topics/GhidRust/help.html`` 
Thanks you

**Comment by p2lu** [comment]
Switched to Ghidra 10.3 and working

**Comment by DMaroo** [comment]
I am closing this issue since it seems to have been resolved. Please let me know if you are still facing problems.
