### ISSUE TITLE
Loading Ghidra with GhidRust plugin cause it to bug and hang

### ISSUE THREAD

**Issue by LeHackerman** [DMaroo/GhidRust#7]
## Expected Behavior
- Rust Decompiler Window opens succefully.
- Symbol Tree loads correctly.
## Actual Behavior
- Rust Decompiler windows is instantiated but transparent.
- Symbol Tree is stuck in "In Progress ..."
- Casual Hanging of Ghidra and sometimes the OS
- Code Browser startup is slower
## Steps to Reproduce the Problem
  
  1. Add Extension
  2. Restart Ghidra
  3. Open file
  4. Run "Open Decompiler"

## Specifications

  - Ghidra Version : 10.3.2
  - Platform : Linux 6.3.0
  - Subsystem : Kali Linux 2023.2

**Comment by DMaroo** [comment]
Hey, thanks for reporting this. If possible, could you provide the binary you're analyzing so I can try to reproduce and debug the hang?

**Comment by LeHackerman** [comment]
Yeah sure, I'll send it by email if you don't mind ?

**Comment by DMaroo** [comment]
Hi, I tested it on my machine. It does take time and CPU to scan the entire binary, but I was able to open, analyze and see decompiled Rust code after it was done analyzing. Could you try disabling the Rust libstd detection analyzer? You can disable it by removing the tickmark from the analyzers menu when you load the binary, as shown below:

![image](https://github.com/DMaroo/GhidRust/assets/72350048/b9a6de37-f13e-452b-9a37-e2e36cc51f9a)

Please let me know if the problem still persists after this.

**Comment by DMaroo** [comment]
Closing because stale.
